name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-release:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Extract version from tag
      id: version
      run: |
        $tag = "${{ github.ref_name }}"
        $version = $tag -replace '^v', ''
        Write-Output "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
      shell: powershell

    - name: Restore
      run: dotnet restore
      
    - name: Build
      run: .\make.bat ${{ steps.version.outputs.version }}

    - name: Create Release and Upload Installer
      uses: softprops/action-gh-release@v2.0.8
      with:
        draft: true
        tag_name: ${{ github.ref_name }}
        name: LenovoLegionToolkit [${{ steps.version.outputs.version }}]
        body: |
          ## Release Notes
          Version ${{ steps.version.outputs.version }}
          
          [View changes](https://github.com/your-username/your-repo/compare/previous-tag...${{ github.ref_name }})
        files: build_installer/LenovoLegionToolkitSetup.exe
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: installer-v${{ steps.version.outputs.version }}
        path: build_installer/LenovoLegionToolkitSetup.exe
