name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-release:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Extract version from tag
      id: version
      run: |
        VERSION="${GITHUB_REF#refs/tags/v}"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Restore
      run: dotnet restore
      
    - name: Build
      run: .\make.bat ${{ steps.version.outputs.version }}
      
    - name: Verify installer exists
      run: |
        if (-not (Test-Path "build_installer\LenovoLegionToolkitSetup.exe")) {
          Write-Error "Installer not found!"
          exit 1
        }
        
    - name: Create Release and Upload Installer
      uses: softprops/action-gh-release@v2.0.8
      with:
        tag_name: ${{ github.ref_name }}
        name: LenovoLegionToolkit v${{ steps.version.outputs.version }}
        body: |
          ## Release Notes
          Version ${{ steps.version.outputs.version }}
        files: build_installer/LenovoLegionToolkitSetup.exe
        token: ${{ secrets.GITHUB_TOKEN }}
