name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-release:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Set version
      id: set_version
      run: |
        if ("${{ github.event_name }}" -eq "workflow_dispatch") {
            $version = "${{ github.event.inputs.version }}"
        } else {
            $tag = "${{ github.ref_name }}"
            $version = $tag -replace '^v', ''
        }
        Write-Output "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
      shell: powershell

    - name: Restore
      run: dotnet restore
      
    - name: Build
      run: .\make.bat ${{ steps.set_version.outputs.version }}
      
    - name: Verify installer
      run: |
        $installerPath = "build_installer\LenovoLegionToolkitSetup.exe"
        if (-not (Test-Path $installerPath)) {
          Write-Error "Installer file not found at $installerPath"
          exit 1
        }
      shell: powershell
        
    - name: Create Release and Upload Installer
      uses: softprops/action-gh-release@v2.0.8
      with:
        draft: true
        tag_name: ${{ steps.set_version.outputs.version }}
        name: LenovoLegionToolkit [${{ steps.set_version.outputs.version }}]
        body: |
          ## Release Notes
          Version ${{ steps.set_version.outputs.version }}
        files: build_installer/LenovoLegionToolkitSetup.exe
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: installer-v${{ steps.set_version.outputs.version }}
        path: build_installer/LenovoLegionToolkitSetup.exe
