name: Release

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-release:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore
      
    - name: Build
      run: .\make.bat latest

    - name: Create Release and Upload Installer
      uses: softprops/action-gh-release@v2.0.8
      with:
        tag_name: latest
        name: LenovoLegionToolkit v${{ steps.version.outputs.version }}
        body: |
          ## Release Notes
          Version ${{ steps.version.outputs.version }}
        files: build_installer/LenovoLegionToolkitSetup.exe
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: installer
        path: build_installer/LenovoLegionToolkitSetup.exe
